---
sink:
  identifier: "io.duzzy.plugin.sink.AzureDatalakeStorageSink"
  account_name: "your-storage-account-name"
  container: "duzzy-test"
  blob_name: "example.json"
  serializer:
    identifier: "io.duzzy.plugin.serializer.JsonSerializer"