---
sink:
  identifier: "io.duzzy.plugin.sink.DuckdbSink"
  serializer:
    identifier: "io.duzzy.plugin.serializer.SqlSerializer"
    table_name: "my_table"
  url: "jdbc:duckdb:/tmp/my_database"
  fail_on_error: true