---
sink:
  identifier: "io.duzzy.plugin.sink.ConsoleSink"
  serializer:
    identifier: "io.duzzy.plugin.serializer.ParquetSerializer"
    name: "avro_name"
    namespace: "avro_namespace"
    schema_file: "docs/blueprints/avro-schemas/example.avsc"